command:
  - uvicorn
  - backend.app.main:app
  - --host
  - "0.0.0.0"
  - --port
  - "8080"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "c2abb17a6c9e6bc0"
  - name: APP_CATALOG
    value: "zivile"
  - name: APP_SCHEMA
    value: "workspace_guardian"
  - name: APP_VERSION
    value: "1.0.0"
  - name: PYTHONPATH
    value: "."

# Static file serving for frontend
static_dirs:
  "/": "frontend/dist"

# Resource limits
resources:
  cpu: "2"
  memory: "4Gi"

